version: '3.8'

services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: banking_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  tracking-app:
<<<<<<< HEAD
    build: ./tracking-app
=======
    build: .
    container_name: tracking-app
    depends_on: [mysql, kafka]
>>>>>>> 9a842f358eab392ffe54aafe4e39fae449fefa2a
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
<<<<<<< HEAD
    depends_on: [mysql, kafka]

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [mysql, kafka]
=======

>>>>>>> 9a842f358eab392ffe54aafe4e39fae449fefa2a
